[package]
name = "geom_2d"
version = "0.1.0"
authors = ["Gijs Burghoorn <g.burghoorn@gmail.com>"]
edition = "2018"
description = "A Rust Library for basic 2D Geometric Definitions"
repository = "https://github.com/coastalwhite/Geom2D"

[dependencies]
